Repository ChiSym/genlm-backend, pull requests merged in 2025-02, with the labels that each got.

#15 fix output dim of mass_sum for parallel trie
  genlm_backend/trie/parallel.py
Labels: 1 min review

#16 simplify trie
  genlm_backend/trie/base.py
  genlm_backend/trie/parallel.py
  tests/test_trie.py
Labels: 1 min review

#17 lint
  genlm_backend/trie/base.py
Labels: 1 min review

#18 Add code coverage step to repo
  .github/workflows/coverage.yml
  .github/workflows/docs.yml
  .github/workflows/pytest.yml
  README.md
  pyproject.toml
Labels: 5 min review

#19 Fix codecov badge URL
  README.md
  docs/index.md
Labels: 1 min review, safe-change

#20 Add release action, dynamic versioning
  .github/workflows/release.yml
  pyproject.toml
Labels: 5 min review
