Repository ChiSym/genlm-backend, pull requests merged in 2025-01, with the labels that each got.

#3 Add support for GPU test runner [in progress]
  .github/workflows/pytest.yml
Labels: 5 min review

#4 Properly escape variables in pytest.yml
  .github/workflows/pytest.yml
Labels: 1 min review

#5 Add pre-commit hooks, ruff linter, ruff github action
  .github/workflows/docs.yml
  .github/workflows/pytest.yml
  .github/workflows/ruff.yml
  .pre-commit-config.yaml
  DEVELOPING.md
  README.md
  benchmark/README.md
  benchmark/benchmark_backend.py
  benchmark/benchmark_mass_sum.py
  benchmark/benchmark_optimizations.py
  benchmark/benchmark_prefix_caching.py
  benchmark/util.py
  docs/gen_reference_page.py
  docs/index.md
  genlm_backend/cache.py
  genlm_backend/llm/__init__.py
  genlm_backend/llm/base.py
  genlm_backend/llm/hf.py
  genlm_backend/llm/vllm.py
  genlm_backend/llm/vllm_reference.py
  genlm_backend/tokenization/__init__.py
  genlm_backend/tokenization/bytes.py
  genlm_backend/tokenization/vocab.py
  genlm_backend/trie/__init__.py
  genlm_backend/trie/async_impl.py
  genlm_backend/trie/base.py
  genlm_backend/trie/parallel.py
  mkdocs.yml
  setup.py
  tests/conftest.py
  tests/test_cache.py
  tests/test_hf_llm.py
  tests/test_llm.py
  tests/test_llm_agreement.py
  tests/test_trie.py
  tests/test_vocabulary.py
Labels: 30 min review

#6 Don't publish docs on PR, add workflow trigger
  .github/workflows/docs.yml
Labels: 1 min review

#7 Enable ruff linter in pre-commit, CI
  .github/workflows/ruff.yml
  .pre-commit-config.yaml
  README.md
  benchmark/benchmark_prefix_caching.py
  pyproject.toml
  setup.py
  src/genlm_backend/__init__.py
  src/genlm_backend/cache.py
  src/genlm_backend/llm/__init__.py
  src/genlm_backend/llm/base.py
  src/genlm_backend/llm/hf.py
  src/genlm_backend/llm/vllm.py
  src/genlm_backend/llm/vllm_reference.py
  src/genlm_backend/tokenization/__init__.py
  src/genlm_backend/tokenization/bytes.py
  src/genlm_backend/tokenization/vocab.py
  src/genlm_backend/trie/__init__.py
  src/genlm_backend/trie/async_impl.py
  src/genlm_backend/trie/base.py
  src/genlm_backend/trie/parallel.py
  tests/test_cache.py
  tests/test_hf_llm.py
  tests/test_vocabulary.py
Labels: 5 min review

#8 docs are broken
  docs/gen_reference_page.py
Labels: 1 min review

#11 Fix sync methods in vllm and add batch_next_token_logprobs_sync
  genlm_backend/llm/base.py
  genlm_backend/llm/hf.py
  genlm_backend/llm/vllm.py
  tests/test_hf_llm.py
  tests/test_llm.py
Labels: 5 min review

#12 add docstring warning for sync usage (#10)
  genlm_backend/llm/vllm.py
Labels: 1 min review
